using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using MySql.Data.MySqlClient;

public partial class ClassInfo : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
       
        this.SqlDataSource1.ConnectionString = Info.datasource;
        this.SqlDataSource2.ConnectionString = Info.datasource;
        this.SqlDataSource3.ConnectionString = Info.datasource;
        this.SqlDataSource4.ConnectionString = Info.datasource;
        commandte = this.SqlDataSource2.SelectCommand;
        if (!IsPostBack)
        {
            if (Session["UserInfo"] == null)
            {
                Response.Redirect("land.aspx");
            }
            //HttpCookie cookie = Request.Cookies["UserInfo"];
            if (Session["UserInfo"].ToString() != "")
            {
                string[] Data = Session["UserInfo"].ToString().Split(new char[] { '#' });
                Info.userid = Data[0];
                Info.uername = Data[1];
                Info.usertype = Convert.ToInt32(Data[2]);
            }
        }
        Info i = new Info();        
        using (MySqlDataReader read1 = i.SelectCountUnit("Select", " classinfo "," Classid,Courseid ", "1>0"))
        {
            while (read1.Read())
            {
                Info j = new Info();
                Info k = new Info();
                MySqlDataReader read2 = j.SelectCountUnit("Select", " CSrelationship ", " Count(*) AS Exp1 ", " Classid=" + read1.GetInt32(0) + "");
                MySqlDataReader read3 = k.SelectCountUnit("Select", " CourseInfo ", " CourseInfo.StudentCount ", ""+read1.GetInt32(1)+"=CourseInfo.Courseid ");
                if (read2.Read()&&read3.Read())
                {
                   Info.InsertUpdateUnit("Update classinfo Set RemainingNumber=" + read3.GetInt32(0) + "-" + read2.GetInt32(0) + " Where Classid=" + read1.GetInt32(0) + "");
                }
            }
        }
        Info TimeCheck = new Info();
        using (MySqlDataReader read = TimeCheck.SelectCountUnit("Select", " classinfo ", " OpenAnAccount,Classid ", " 1<2 "))
        {
            while (read.Read())
            {
                if (Convert.ToInt32(read.GetDateTime(0).ToString("yyyyMMdd")) <= Convert.ToInt32(System.DateTime.Today.ToString("yyyyMMdd")))
                {
                    Info.InsertUpdateUnit("Update classinfo Set RemainingNumber=0 where Classid=" + read.GetInt32(1));
                }
            }
        }
        if (Info.usertype == 1)
        {
            this.Admin.Visible = true;
            this.AddCourse.Visible = true;
            this.GridView1.AutoGenerateDeleteButton = true;
        }
    }
    private string commandte;
    protected void Button1_Click(object sender, EventArgs e)
    {
        if (CourseText.SelectedItem.Value != "" && RegistartionNumberText.Text != "" && OpeningDateText.Value != "" && TeacherText.SelectedItem.Text != "")
        {
            if (ClassNameText.Text == "")
            {
                ClassNameText.Text = CourseText.SelectedItem.Text;
            }
            Info i = new Info();
            int Classid = 2;
            using (MySqlDataReader read = i.SelectCountUnit("Select", " classinfo ", " Classid ", " Classid=(Select Max(Classid) from classinfo)"))
            {
                if (read.Read())
                {

                    Classid = read.GetInt32(0) + 1;

                }
                read.Close();
            }
            Info.InsertUpdateUnit("Insert Into classinfo(Courseid,ClassName,RemainingNumber,OpenAnAccount,CloseAnAccount,ClassTime,Classid) Values ('" + this.CourseText.SelectedValue + "','" + this.ClassNameText.Text + "','" + this.RegistartionNumberText.Text + "','" + this.OpeningDateText.Value + "','" + this.CloseDateText.Value + "','" + this.ClassTime.Text + "'," + Classid + ") ");
            //Info.InsertUpdateUnit("Insert Into TeacherInfo(TeacherName,Teacherid) values('" + this.TeacherText.Text + "'," + teachid + ")");
            Info.InsertUpdateUnit("Insert Into Tcrelationship(Teacherid,Classid) Values(" + this.TeacherText.SelectedValue + "," + Classid + ")");
            Response.AddHeader("Refresh", "0");
        }
    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        if (this.AddCourseCountText.Text != "" && this.AddCourseCostText.Text != "" && this.AddCourseHourseText.Text != "" && this.AddCourseNameText.Text != "")
        {
            string cmd = "Insert Into CourseInfo(CourseName,StudentCount,ClassHour,CourseCost) Values('" + this.AddCourseNameText.Text + "'," + this.AddCourseCountText.Text + "," + this.AddCourseHourseText.Text + "," + this.AddCourseCostText.Text + ")";
            Info.InsertUpdateUnit(cmd);
        }
        this.AddCoursetd.Visible = false;
        Response.AddHeader("Refresh", "0");
    }

    protected void AddCourse_Click(object sender, EventArgs e)
    {
        this.AddCoursetd.Visible = true;
    }
    protected void Serach_Click(object sender, EventArgs e)
    {
        this.SerachDiv.Visible = true;
    }
    protected void Ok_Click(object sender, EventArgs e)
    {
        string command = this.SqlDataSource2.SelectCommand;
        if (this.CourseInfo.SelectedValue != "")
        {
            command += " And classinfo.Courseid=" + this.CourseInfo.SelectedValue + "";
        }
        if (this.SerachDate.Value != "")
        {
            command += " And classinfo.OpenAnAccount Like '%"+this.SerachDate.Value+"%'";
        }
        if (this.DropDownList1.SelectedItem.Text != "")
        {
            command += " And '" + this.DropDownList1.SelectedValue + "'=TCrelationship.Teacherid And TCrelationship.Classid=classinfo.Classid";
        }
        SqlDataSource2.SelectCommand = command;
        GridView1.DataBind();
    }
    protected void LinkButton1_Click(object sender, EventArgs e)
    {
        this.SqlDataSource2.SelectCommand = commandte;
        GridView1.DataBind();
        this.SerachDiv.Visible = false;
    }
    protected void GridView1_RowDeleted(object sender, GridViewDeletedEventArgs e)
    {

    }
    protected void ClassNameText_TextChanged(object sender, EventArgs e)
    {
        
    }
    protected void CourseText_SelectedIndexChanged(object sender, EventArgs e)
    {
        Info i = new Info();
        string value = this.CourseText.SelectedValue;
        using (MySqlDataReader read = i.SelectCountUnit("Select", " CourseInfo ", " StudentCount ", " Courseid=" + this.CourseText.SelectedValue + ""))
        {
            if (read.Read())
            {
                this.RegistartionNumberText.Text =Convert.ToString(read.GetInt32(0));
            }
            read.Close();
        }
    }
    protected void GridView1_RowDataBound(object sender, GridViewRowEventArgs e)
    {
        //if (Convert.ToInt32((Convert.ToDateTime(((Label)e.Row.FindControl("Label3")).Text)).ToString("yyyyMMdd")) <= Convert.ToInt32(DateTime.Today.ToString("yyyyMMdd")))
        //{
        //    e.Row.ForeColor = System.Drawing.Color.Red;
        //}
    }
}