using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using MySql.Data.MySqlClient;
using System.Data;
using System.Web.UI.HtmlControls;

public partial class Welcom : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        //((SqlDataSource)this.GridView1.FindControl("SqlDataSource1")).ConnectionString = Info.datasource;
        //this.SqlDataSource1.ConnectionString = Info.datasource;
        this.SqlDataSource2.ConnectionString = Info.datasource;
        CommandText = selectcommand+" Where 1>0 ";
        this.Label1.Text = Info.uername;
        if (Info.usertype == 1)
        {
            this.LinkButton3.Visible = true;
            this.GridView1.AutoGenerateDeleteButton = true;
        }
        if (!IsPostBack)
        {
            if (Session["UserInfo"] == null)
            {
                Response.Redirect("land.aspx");
            }
            //HttpCookie cookie = Request.Cookies["UserInfo"];
            if (Session["UserInfo"].ToString() != "")
            {
                string[] Data = Session["UserInfo"].ToString().Split(new char[] { '#' });
                Info.userid = Data[0];
                Info.uername = Data[1];
                Info.usertype = Convert.ToInt32(Data[2]);
            }
            ViewState["ConsultingInfo"] = (DataTable)Info.Gridviewbind(this.GridView1, selectcommand).Tables[0];
            Session.Timeout = 12 * 60;
            Session["TempCommand"] = selectcommand;
        }
        this.GridView1.DataKeyNames = new string[] { "Contactid", "Relationshipid" };
    }
    string selectcommand = "SELECT UserInfo0.Username, ConsultingInfo.ConsultingTime, ConsultingInfo.ParentsCall, ConsultingInfo.Contact, CourseInfo.CourseName, ConsultingInfo.ChildrenSex, ConsultingInfo.Contactid, ConsultingInfo.ChildrenCall, ConsultingInfo.ChildrenAge, ConsultingInfo.School, ConsultingInfo.Remarks, ConsultingInfo.SignUp, ConsultingInfo.Courseid ,CSrelationship.Relationshipid FROM UserInfo0 INNER JOIN ConsultingInfo ON UserInfo0.Userid = ConsultingInfo.Userid INNER JOIN CourseInfo ON ConsultingInfo.Courseid = CourseInfo.Courseid INNER JOIN CSrelationship ON CSrelationship.Contactid=ConsultingInfo.Contactid";

    protected void Button1_Click(object sender, EventArgs e)
    {
        string error = null;
        if(!Info.checktext("PhoneNumber",this.TextBox2.Text))
        {
            error += "电话号码非法! ";
        }
        if(!Info.checktext("N",this.TextBox6.Text))
        {
            error+="年龄必须是数字!";
        }
        if (error != null)
        {
            this.Label2.Text = error;
            this.Label2.Visible = true;
        }
        else
        {
            Info i = new Info();
            string id = System.DateTime.Today.ToString("yyMM") + "0001";
            using (MySqlDataReader read = i.SelectCountUnit("select", " ConsultingInfo ", " Contactid ", "  Contactid=(Select Max(Contactid) From ConsultingInfo)"))
            {
                if (read.Read())
                {
                    int yn=read.GetInt32(0)/10000;
                    if(yn==Convert.ToInt32(System.DateTime.Today.ToString("yyMM")))
                    {
                        int temp = read.GetInt32(0);
                        temp += 1;
                        id = Convert.ToString(temp);
                    }
                }
                read.Close();
            }
            if (Info.userid ==null)
            {
                Response.Redirect("land.aspx");
            }
            Info.InsertUpdateUnit("Insert Into ConsultingInfo(Contactid,Userid,ConsultingTime,ParentsCall,Contact,ChildrenCall,ChildrenSex,ChildrenAge,School,Remarks,Courseid,SignUp) Values (" + id + ",'" + Info.userid + "','" + DateTime.Now + "','" + this.TextBox1.Text + "','" + this.TextBox2.Text + "','" + this.TextBox3.Text + "','" + this.DropDownList2.SelectedItem.Text + "','" + this.TextBox6.Text + "','" + this.TextBox4.Text + "','" + Info.remarks + "','" + this.DropDownList4.SelectedValue + "',0)");
            Info.InsertUpdateUnit("Insert Into CSrelationship(Classid,Contactid) Values (0,"+id+")");
            Info.remarks = null;
            Response.AddHeader("Refresh", "0");
        }
    }

    protected void LinkButton1_Click1(object sender, EventArgs e)
    {
        this.div2.Visible = true;
    }
    protected void uButton_Click(object sender, EventArgs e)
    {
        string command =selectcommand+" Where 1>0 ";
        if (this.AgeDorpDownList1.SelectedItem.Text != "")
        {
            command += " And ChildrenAge >= '"+this.AgeDorpDownList1.SelectedItem.Text+"'";
        }
        if (this.AgeDorpDownList2.SelectedItem.Text != "")
        {
            command += " And ChildrenAge <='"+this.AgeDorpDownList2.SelectedItem.Text+"'";
        }
        if (this.ShoolTextbox.Text != "")
        {
            command += " And School Like '%"+this.ShoolTextbox.Text+"%'";
        }
        if (this.ParentsCallTextBox.Text != "")
        {
            command += " And ParentsCall Like '%"+this.ParentsCallTextBox.Text+"%'";
        }
        if (this.ChildrenCallTextBox.Text != "")
        {
            command += " And ChildrenCall Like '%" + this.ChildrenCallTextBox.Text + "%'";
        }
        if (this.SexDorpDownList.SelectedItem.Text != "")
        {
            command += " And ChildrenSex ='"+this.SexDorpDownList.SelectedItem.Text+"'";
        }
        if (this.RemarksTextBox.Text != "")
        {
            command += " And Remarks Like '%" +this.RemarksTextBox.Text+ "%'";
        }
        if (this.d12.Value != "")
        {
            command += " And ConsultingTime >= '"+this.d12.Value+"'";
        }
        if (this.d11.Value != "")
        {
            command += " And ConsultingTime <='"+this.d11+"'";
        }
        if (this.SignUpDorpDownList.SelectedItem.Text != "")
        {
            command += " And SignUp ='"+this.SignUpDorpDownList.SelectedItem.Value+"'";
        }
        ViewState["ConsultingInfo"] = (DataTable)Info.Gridviewbind(this.GridView1, command).Tables[0];
        Session["TempCommand"] = command;
    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        ViewState["ConsultingInfo"]=(DataTable)Info.Gridviewbind(this.GridView1, CommandText + " And ConsultingInfo.Contact Like '%"+this.TextBox7.Text+"%'").Tables[0];
        Session["TempCommand"]=CommandText + " And ConsultingInfo.Contact Like '%"+this.TextBox7.Text+"%'";
    }
    protected void LinkButton2_Click(object sender, EventArgs e)
    {
        this.div2.Visible = false;
    }
    protected void LinkButton3_Click(object sender, EventArgs e)
    {
        string command = CommandText + " And ConsultingInfo.Courseid="+this.DropDownList1.SelectedValue+"";
        Session["TempCommand"] = CommandText + " And ConsultingInfo.Courseid=" + this.DropDownList1.SelectedValue + "";
        //this.SqlDataSource1.SelectCommand = command;
        //this.GridView1.DataBind();
        ViewState["ConsultingInfo"] = (DataTable)Info.Gridviewbind(this.GridView1, command).Tables[0];
    }
    protected void Button3_Click(object sender, EventArgs e)
    {
      
        
    }
    protected void TextBox8_TextChanged(object sender, EventArgs e)
    {
    }
    protected void TextBox9_TextChanged(object sender, EventArgs e)
    {

    }
    protected void LinkButton3_Click1(object sender, EventArgs e)
    {
        Response.Redirect("AddUser.aspx");
    }
    protected void Button4_Click(object sender, EventArgs e)
    {
        Response.Write("<script> window.open(\"ClassInfo.aspx\")</script>");
    }
    protected void Button5_Click(object sender, EventArgs e)
    {
        Response.Redirect("student.aspx");
    }
    protected void RadioButton1_CheckedChanged(object sender, EventArgs e)
    {

    }
    protected void LinkButton4_Click(object sender, EventArgs e)
    {
        this.Remarks.Visible = true;
    }
    protected void RemarkButton_Click(object sender, EventArgs e)
    {

        Info.remarks = this.TextBox10.Text;
        this.Remarks.Visible = false;
    }
    private string CommandText;
    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {

    }
    protected void GridView1_PageIndexChanging(object sender, GridViewPageEventArgs e)
    {
        this.GridView1.PageIndex = e.NewPageIndex;
        this.GridView1.DataSource = (DataTable)ViewState["ConsultingInfo"];
        this.GridView1.DataBind();
    }
    protected void GridView1_RowEditing(object sender, GridViewEditEventArgs e)
    {
        this.GridView1.EditIndex = e.NewEditIndex;
        ViewState["ConsultingInfo"] = (DataTable)Info.Gridviewbind(this.GridView1, Session["TempCommand"].ToString()).Tables[0];
        //this.GridView1.DataSource = (DataTable)ViewState["ConsultingInfo"];
        //this.GridView1.DataBind();
    }
    protected void GridView1_RowCancelingEdit(object sender, GridViewCancelEditEventArgs e)
    {
       //ViewState["ConsultingInfo"] = (DataTable)Info.Gridviewbind(this.GridView1, selectcommand).Tables[0];
        Response.Redirect("Welcom.aspx");
    }
    protected void GridView1_RowUpdating(object sender, GridViewUpdateEventArgs e)
    {
        //int p = 0;
        //if (Info.usertype == 1)
        //{
        //    p++;
        //}
        string ConsultingInfoid = this.GridView1.DataKeys[e.RowIndex].Values[0].ToString();
        string Relapibshipid = this.GridView1.DataKeys[e.RowIndex].Values[1].ToString();
        string ConsultingTime = "'"+((HtmlInputText)this.GridView1.Rows[e.RowIndex].FindControl("TextBox12")).Value+"'";
        string ParentCall = "'"+((TextBox)this.GridView1.Rows[e.RowIndex].FindControl("ParentsCall_TextBox")).Text+"'";
        string Contact = "'"+((TextBox)this.GridView1.Rows[e.RowIndex].FindControl("Contact_TextBox")).Text+"'";
        string CCourseid = ((DropDownList)this.GridView1.Rows[e.RowIndex].FindControl("DropDownList6")).SelectedValue;
        string ChildrenSex = "'"+((TextBox)this.GridView1.Rows[e.RowIndex].Cells[7].Controls[0]).Text+"'";
        string ChildrenCall = "'"+((TextBox)this.GridView1.Rows[e.RowIndex].Cells[8].Controls[0]).Text+"'";
        string ChildrenAge = ((TextBox)this.GridView1.Rows[e.RowIndex].Cells[9].Controls[0]).Text;
        string School = "'"+((TextBox)this.GridView1.Rows[e.RowIndex].Cells[10].Controls[0]).Text+"'";
        string Remarks = "'"+((TextBox)this.GridView1.Rows[e.RowIndex].FindControl("TextBox2")).Text+"'";
        string SignUp = "0";
        if (School == null || School == "")
        {
            School = "null";
        }
        else if (ParentCall == null || ParentCall == "")
        {
            ParentCall = "null";
        }
        else if (Info.checktext("PhoneNumber", Contact)||Contact==null)
        {
            Literal TxtMsg = new Literal();
            TxtMsg.Text = "<script>alert('电话号码非法!')</script>";
            Page.Controls.Add(TxtMsg);
        }
        else if (ChildrenCall == null || ChildrenCall == "")
        {
            ChildrenCall = "null";
        }
        else if (!Info.checktext("N", ChildrenAge) || ChildrenAge == null)
        {
            Literal TxtMsg=new Literal();
            TxtMsg.Text = "<script>alert('年龄不可为空并且必须是纯数字!')</script>";
            Page.Controls.Add(TxtMsg);
        }
        else if (ConsultingInfoid == null || ConsultingInfoid == "")
        {
            Literal TxtMsg = new Literal();
            TxtMsg.Text = "<script>alert('无法获取键值,更新失败!')</script>";
            Page.Controls.Add(TxtMsg);
        }
        else
        {
            string UpdateCommand = "Update ConsultingInfo set ConsultingTime=" + ConsultingTime + ",ParentsCall=" + ParentCall + ",Contact=" + Contact + ",Courseid=" + CCourseid + ", ChildrenSex=" + ChildrenSex + ", ChildrenCall=" + ChildrenCall + ",ChildrenAge=" + ChildrenAge + ",School=" + School + ",Remarks=" + Remarks + ",SignUp=" + SignUp + " where Contactid="+this.GridView1.DataKeys[e.RowIndex].Values[0].ToString();
            Info.InsertUpdateUnit(UpdateCommand);
            ViewState["ConsultingInfo"] = (DataTable)Info.Gridviewbind(this.GridView1, selectcommand).Tables[0];
            Response.Redirect("Welcom.aspx");
        }
    }
    protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
    {
        string Consultingid = this.GridView1.DataKeys[e.RowIndex].Values[0].ToString();
        string Relationshipid = this.GridView1.DataKeys[e.RowIndex].Values[1].ToString();
        string DelConsultingCommand = "Delete ConsultingInfo Where Contactid="+Consultingid+"";
        string DelCSrelationship = "Delete CSrelationship where Relationshipid="+Relationshipid+"";
        if (Consultingid == null || Consultingid == "")
        {
            Literal TxtMsg = new Literal();
            TxtMsg.Text = "<script>alert('无法获取键值,删除失败!')</script>";
            Page.Controls.Add(TxtMsg);
        }
        else
        {
            Info.InsertUpdateUnit(DelConsultingCommand);
            //ViewState["ConsultingInfo"] = (DataTable)Info.Gridviewbind(this.GridView1, selectcommand).Tables[0];
            Response.Redirect("Welcom.aspx");
        }
    }
    protected void new_Click(object sender, EventArgs e)
    {
        Response.Redirect("Welcom.aspx");
    }
}